export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  PROGRAMS: '/programs',
  TRAINERS: '/trainers',
  PRICING: '/pricing',
  GALLERY: '/gallery',
  BLOG: '/blog',
  CONTACT: '/contact',
  LOGIN: '/login',
  SIGNUP: '/signup',
};

export const STATS = [
  { value: 15000, label: 'Active Members', suffix: '+' },
  { value: 98, label: 'Success Rate', suffix: '%' },
  { value: 50, label: 'Expert Trainers', suffix: '+' },
  { value: 10, label: 'Years Experience', suffix: '+' },
];

export const PROGRAMS = [
  {
    id: 1,
    title: 'Strength Training',
    category: 'Strength',
    description: 'Build muscle mass and increase overall strength with our progressive overload programs.',
    duration: '12 weeks',
    level: 'Intermediate',
    image: 'https://images.pexels.com/photos/1552242/pexels-photo-1552242.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: 2,
    title: 'HIIT Cardio',
    category: 'Cardio',
    description: 'High-intensity interval training to burn fat and boost cardiovascular endurance.',
    duration: '8 weeks',
    level: 'All Levels',
    image: 'https://images.pexels.com/photos/4162449/pexels-photo-4162449.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: 3,
    title: 'Yoga & Flexibility',
    category: 'Flexibility',
    description: 'Improve flexibility, balance, and mental clarity through guided yoga sessions.',
    duration: '6 weeks',
    level: 'Beginner',
    image: 'https://images.pexels.com/photos/3822165/pexels-photo-3822165.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: 4,
    title: 'CrossFit Elite',
    category: 'CrossFit',
    description: 'Advanced functional fitness combining strength, cardio, and gymnastics movements.',
    duration: '16 weeks',
    level: 'Advanced',
    image: 'https://images.pexels.com/photos/3757376/pexels-photo-3757376.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: 5,
    title: 'Boxing & MMA',
    category: 'Combat',
    description: 'Learn striking techniques while getting an intense full-body workout.',
    duration: '10 weeks',
    level: 'Intermediate',
    image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: 6,
    title: 'Athletic Performance',
    category: 'Sports',
    description: 'Sport-specific training to enhance speed, agility, and explosive power.',
    duration: '12 weeks',
    level: 'Advanced',
    image: 'https://images.pexels.com/photos/3253501/pexels-photo-3253501.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
];

export const TRAINERS = [
  {
    id: 1,
    name: 'Marcus Johnson',
    specialty: 'Strength & Conditioning',
    experience: '12 years',
    bio: 'Former Olympic athlete specializing in strength training and athletic performance.',
    image: 'https://images.pexels.com/photos/4754146/pexels-photo-4754146.jpeg?auto=compress&cs=tinysrgb&w=600',
    instagram: '@marcusjfit',
    certifications: ['CSCS', 'USAW', 'FMS'],
  },
  {
    id: 2,
    name: 'Sarah Chen',
    specialty: 'Yoga & Mindfulness',
    experience: '8 years',
    bio: 'Certified yoga instructor bringing balance between physical fitness and mental wellness.',
    image: 'https://images.pexels.com/photos/3775566/pexels-photo-3775566.jpeg?auto=compress&cs=tinysrgb&w=600',
    instagram: '@sarahyogaflow',
    certifications: ['RYT-500', 'YACEP', 'Meditation Coach'],
  },
  {
    id: 3,
    name: 'David Torres',
    specialty: 'HIIT & CrossFit',
    experience: '10 years',
    bio: 'CrossFit Level 3 trainer focused on functional fitness and metabolic conditioning.',
    image: 'https://images.pexels.com/photos/4761352/pexels-photo-4761352.jpeg?auto=compress&cs=tinysrgb&w=600',
    instagram: '@davidcrossfit',
    certifications: ['CF-L3', 'NASM-CPT', 'Sports Nutrition'],
  },
  {
    id: 4,
    name: 'Emma Wilson',
    specialty: 'Boxing & Combat',
    experience: '7 years',
    bio: 'Professional boxer turned coach, specializing in striking and defensive techniques.',
    image: 'https://images.pexels.com/photos/3775164/pexels-photo-3775164.jpeg?auto=compress&cs=tinysrgb&w=600',
    instagram: '@emmafightfit',
    certifications: ['USA Boxing Coach', 'ISSA-CPT'],
  },
];

export const PRICING_PLANS = [
  {
    id: 1,
    name: 'Starter',
    monthlyPrice: 49,
    yearlyPrice: 470,
    popular: false,
    features: [
      'Access to gym facilities',
      'Basic equipment usage',
      'Locker room access',
      'Mobile app access',
      'Fitness assessment',
    ],
  },
  {
    id: 2,
    name: 'Pro',
    monthlyPrice: 89,
    yearlyPrice: 890,
    popular: true,
    features: [
      'Everything in Starter',
      'Unlimited group classes',
      '2 personal training sessions/month',
      'Nutrition consultation',
      'Priority booking',
      'Guest pass (2/month)',
    ],
  },
  {
    id: 3,
    name: 'Elite',
    monthlyPrice: 149,
    yearlyPrice: 1490,
    popular: false,
    features: [
      'Everything in Pro',
      'Unlimited personal training',
      'Custom meal planning',
      'Recovery & spa access',
      'Private locker',
      'Unlimited guest passes',
      '24/7 gym access',
    ],
  },
];

export const BLOG_POSTS = [
  {
    id: 1,
    title: '10 Essential Exercises for Building Muscle Mass',
    excerpt: 'Discover the fundamental movements that form the foundation of any effective muscle-building program.',
    category: 'Training',
    author: 'Marcus Johnson',
    date: '2024-03-15',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/3837757/pexels-photo-3837757.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: 2,
    title: 'Nutrition 101: Fueling Your Fitness Journey',
    excerpt: 'Learn how to optimize your diet to support your training goals and maximize results.',
    category: 'Nutrition',
    author: 'Sarah Chen',
    date: '2024-03-12',
    readTime: '7 min',
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: 3,
    title: 'The Science Behind HIIT Training',
    excerpt: 'Understanding the metabolic benefits and proper implementation of high-intensity interval training.',
    category: 'Cardio',
    author: 'David Torres',
    date: '2024-03-10',
    readTime: '6 min',
    image: 'https://images.pexels.com/photos/4162487/pexels-photo-4162487.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: 4,
    title: 'Recovery Strategies for Optimal Performance',
    excerpt: 'Why rest and recovery are just as important as your training sessions.',
    category: 'Recovery',
    author: 'Emma Wilson',
    date: '2024-03-08',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/3822906/pexels-photo-3822906.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: 5,
    title: 'Mind-Muscle Connection: Training Smarter',
    excerpt: 'How focusing on the mind-muscle connection can dramatically improve your results.',
    category: 'Training',
    author: 'Marcus Johnson',
    date: '2024-03-05',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/3760263/pexels-photo-3760263.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: 6,
    title: 'Flexibility Training: Beyond the Basics',
    excerpt: 'Advanced stretching techniques to improve mobility and prevent injuries.',
    category: 'Flexibility',
    author: 'Sarah Chen',
    date: '2024-03-01',
    readTime: '6 min',
    image: 'https://images.pexels.com/photos/3822694/pexels-photo-3822694.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
];

export const GALLERY_IMAGES = [
  { id: 1, url: 'https://images.pexels.com/photos/1552252/pexels-photo-1552252.jpeg?auto=compress&cs=tinysrgb&w=800', category: 'gym' },
  { id: 2, url: 'https://images.pexels.com/photos/1552242/pexels-photo-1552242.jpeg?auto=compress&cs=tinysrgb&w=800', category: 'training' },
  { id: 3, url: 'https://images.pexels.com/photos/3076509/pexels-photo-3076509.jpeg?auto=compress&cs=tinysrgb&w=800', category: 'gym' },
  { id: 4, url: 'https://images.pexels.com/photos/4162487/pexels-photo-4162487.jpeg?auto=compress&cs=tinysrgb&w=800', category: 'cardio' },
  { id: 5, url: 'https://images.pexels.com/photos/3253501/pexels-photo-3253501.jpeg?auto=compress&cs=tinysrgb&w=800', category: 'training' },
  { id: 6, url: 'https://images.pexels.com/photos/3757376/pexels-photo-3757376.jpeg?auto=compress&cs=tinysrgb&w=800', category: 'crossfit' },
  { id: 7, url: 'https://images.pexels.com/photos/3822165/pexels-photo-3822165.jpeg?auto=compress&cs=tinysrgb&w=800', category: 'yoga' },
  { id: 8, url: 'https://images.pexels.com/photos/3837757/pexels-photo-3837757.jpeg?auto=compress&cs=tinysrgb&w=800', category: 'training' },
  { id: 9, url: 'https://images.pexels.com/photos/4164761/pexels-photo-4164761.jpeg?auto=compress&cs=tinysrgb&w=800', category: 'gym' },
  { id: 10, url: 'https://images.pexels.com/photos/4162449/pexels-photo-4162449.jpeg?auto=compress&cs=tinysrgb&w=800', category: 'cardio' },
  { id: 11, url: 'https://images.pexels.com/photos/3822906/pexels-photo-3822906.jpeg?auto=compress&cs=tinysrgb&w=800', category: 'recovery' },
  { id: 12, url: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=800', category: 'boxing' },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Michael Rodriguez',
    role: 'Software Engineer',
    content: 'This gym completely transformed my approach to fitness. The trainers are world-class and the facilities are unmatched.',
    rating: 5,
    image: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
  {
    id: 2,
    name: 'Jennifer Park',
    role: 'Marketing Director',
    content: 'Best investment in my health. The community here is incredibly supportive and motivating.',
    rating: 5,
    image: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
  {
    id: 3,
    name: 'Alex Thompson',
    role: 'Entrepreneur',
    content: 'From cardio to strength training, everything is top-tier. I have achieved goals I never thought possible.',
    rating: 5,
    image: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
];
